### ISSUE TITLE
Enable passing list of comands to execute on setup steps

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/redisbench-admin#111]
add `init_commands`.
- should issue the commands before starting the benchmark
- the `init_commands` property should be added in between: https://github.com/RedisLabsModules/redisbench-admin/blob/master/redisbench_admin/run_local/run_local.py#L103

```yaml
version: 0.2

dbconfig:
  - dataset: "remote_link" 
  - init_commands:
      - 'GRAPH.QUERY xx yy'
      - 'GRAPH.QUERY xx yy'
```

Example of yaml parsing test:
https://github.com/RedisLabsModules/redisbench-admin/blob/master/tests/test_benchmark_config.py#L49
