### ISSUE TITLE
redis-benchmark -r option not being used

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/redisbench-admin#112]
Sample specification:
```
version: 0.2
name: "bf_add_cap10K_err0.01"
description: "bf.add test __rand_int__"
remote:
 - type: oss-standalone
 - setup: redisearch-m5d
clientconfig:
  - tool: redis-benchmark
  - min-tool-version: "6.2.0"
  - parameters:
    - clients: 16
    - requests: 1000000000
    - threads: 2
    - pipeline: 1
    - r: 100000
    - command: 'bf.add test __rand_int__'
```
generated command:
```
/usr/local/bin/redis-benchmark -h localhost -p 6379 --csv -e -c 16 -n 1000000000 --threads 2 -P 1 bf.add test __rand_int__
```
