### ISSUE TITLE
Enabled specifying dataset_load_timeout_secs property

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/redisbench-admin#130]
dataset_load_timeout should be part of `dbconfig` settings. By default ( if not present it should have a 120secs timeout )

sample:

```yml
dbconfig:
  - dataset: "https://s3.amazonaws.com/benchmarks.redislabs/redistimeseries/tsbs/datasets/devops/scale100/devops-scale100-4days.rdb"
  - dataset_load_timeout_secs: 1200
 ```
