### ISSUE TITLE
metadata property not being used on export tool

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabsModules/redisbench-admin#224]
Sample yml containing metadata:
```
version: 0.5
exporter:
  redistimeseries:
    timemetric: "$.'ALL STATS'.Runtime.'Start time'"
    metrics:
      - "$.'BEST RUN RESULTS'.Totals.'Ops/sec'"
  
metadata:
  label1: value1
  label2: value2
```
